### ISSUE TITLE
Possible Stylesheet Organization Regression in 3.1

### ISSUE THREAD

**Issue by philiparthurmoore** [Automattic/Genericons#38]
I've just updated to the latest version of Genericons (3.1) and noticed that the organization of the CSS has changed slightly, such that icon blocks are no longer grouped by theme but put into one large list under `Individual icons`. [This](https://github.com/Automattic/Genericons/blob/0baeeca02933cc5f269d09a93130bf9e24d120cf/genericons.css) is what the old stylesheet looked like, which made understanding the icons very easy. There's a block for `Post formats`, `Social icons`, and so forth.

``` css
/* Meta icons */
.genericon-comment:before {         content: '\f300'; }
.genericon-category:before {        content: '\f301'; }
.genericon-tag:before {             content: '\f302'; }
.genericon-time:before {            content: '\f303'; }
.genericon-user:before {            content: '\f304'; }
.genericon-day:before {             content: '\f305'; }
.genericon-week:before {            content: '\f306'; }
.genericon-month:before {           content: '\f307'; }
.genericon-pinned:before {          content: '\f308'; }
```

In the [new stylesheet](https://github.com/Automattic/Genericons/blob/master/genericons/genericons.css) everything is blocked together so it's hard to understand which icons belong to which group.

``` css
/**
 * Individual icons
 */
.genericon-404:before { content: "\f423"; }
.genericon-aside:before { content: "\f101"; }
.genericon-attachment:before { content: "\f416"; }
.genericon-audio:before { content: "\f109"; }
.genericon-bold:before { content: "\f471"; }
.genericon-book:before { content: "\f444"; }
.genericon-cart:before { content: "\f447"; }
.genericon-category:before { content: "\f301"; }
.genericon-chat:before { content: "\f108"; }
.genericon-checkmark:before { content: "\f418"; }
.genericon-close:before { content: "\f405"; }
.genericon-close-alt:before { content: "\f406"; }
```

Is this due to the way that the file is being generated or a design decision? Would you be open to re-blocking the icons into themes or sequentially so that we're able to more easily understand which selectors belong to which group?
